MEDICAL_DISCLAIMER = (
    "\n\n---\n"
    "DISCLAIMER: This information is generated by an AI assistant for educational purposes "
    "only and does not constitute medical advice, diagnosis, or treatment. "
    "Always consult a qualified healthcare professional before making any health decisions."
)

CRITICAL_KEYWORDS = [
    "diabetes", "cardiac", "kidney failure", "critical",
    "emergency", "hospital", "immediate",
]


def wrap_with_disclaimer(response: str) -> str:
    return response + MEDICAL_DISCLAIMER


def check_critical(response: str) -> bool:
    """Flag responses that may need urgent referral."""
    lower = response.lower()
    return any(kw in lower for kw in CRITICAL_KEYWORDS)


def apply_guardrails(response: str) -> dict:
    is_critical = check_critical(response)
    if is_critical:
        response = "URGENT: Please consult a physician immediately.\n\n" + response
    return {
        "content": wrap_with_disclaimer(response),
        "requires_doctor": is_critical,
    }
